---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: content/posts/_index.md
  templates:
  - post
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
  exclude: content/projects/_index.md
  templates:
  - project
- type: directory
  path: content/people
  label: People
  create: all
  match: "**/*"
  templates:
  - person
upload_dir: ''
public_path: http://res.cloudinary.com/forestrydemo1/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.42.1
